// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSResources
{
        public const string achievement_getting_used = "CgkI5ZSNkaUNEAIQDA"; // <GPGSID>
        public const string achievement_thousands = "CgkI5ZSNkaUNEAIQBg"; // <GPGSID>
        public const string achievement_impressive = "CgkI5ZSNkaUNEAIQDQ"; // <GPGSID>
        public const string achievement_freakish = "CgkI5ZSNkaUNEAIQEQ"; // <GPGSID>
        public const string achievement_4k = "CgkI5ZSNkaUNEAIQBw"; // <GPGSID>
        public const string achievement_the_beginning = "CgkI5ZSNkaUNEAIQAQ"; // <GPGSID>
        public const string achievement_millions = "CgkI5ZSNkaUNEAIQEA"; // <GPGSID>
        public const string achievement_really_tiled = "CgkI5ZSNkaUNEAIQBA"; // <GPGSID>
        public const string achievement_500k = "CgkI5ZSNkaUNEAIQDw"; // <GPGSID>
        public const string achievement_tiled = "CgkI5ZSNkaUNEAIQAw"; // <GPGSID>
        public const string achievement_just_warming_up = "CgkI5ZSNkaUNEAIQCw"; // <GPGSID>
        public const string achievement_50k = "CgkI5ZSNkaUNEAIQDg"; // <GPGSID>
        public const string achievement_tens_of_thousands = "CgkI5ZSNkaUNEAIQCA"; // <GPGSID>
        public const string achievement_hundreads = "CgkI5ZSNkaUNEAIQBQ"; // <GPGSID>
        public const string achievement_millionaire = "CgkI5ZSNkaUNEAIQCg"; // <GPGSID>
        public const string achievement_just_quit = "CgkI5ZSNkaUNEAIQEg"; // <GPGSID>
        public const string achievement_combined = "CgkI5ZSNkaUNEAIQAg"; // <GPGSID>
        public const string achievement_hundreads_of_thousands = "CgkI5ZSNkaUNEAIQCQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI5ZSNkaUNEAIQAA"; // <GPGSID>

}

